name: flutter_envied
description: How to use Envied with multi environments.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  envied: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  envied_generator: 0.3.0
  build_runner: 2.3.3

flutter:
  uses-material-design: true




